name: Deploy database

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install dependencies
        working-directory: database
        run: npm install

      - name: Deploy CDKTF stack
        working-directory: database
        run: npx cdktf deploy --auto-approve
