name: Deploy database

on:
  pull_request:
    branches:
      - main
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: database

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with: 
          node-version: 18.x

      - name: Install CDKTF CLI
        run: npm install -g cdktf-cli

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - name: Install dependencies
        run: npm ci

      # If you use providers or modules that are not pre-built, you can install them here
      - name: Generate bindings for providers and modules
        run: cdktf get

      - name: Run Tests
        run: npm test

      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy
        run: cdktf deploy --auto-approve
