name: Deploy database

on:
  pull_request:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-west-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory:   ./database

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      
      - name: Install CDKTF CLI
        run: npm install -g cdktf-cli

      - name: Install dependencies
        run: npm install

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Run Terraform CDK
        run: npx cdktf deploy --auto-approve
        
